[profile.default]
src = "src"
out = "out"
libs = ["lib"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


# Specify the Solidity version explicitly
solc_version = "0.8.26"


# Enable intermediate representation (IR) pipeline to optimize contracts
via_ir = true


# Disable auto-detection of Solidity compiler to enforce the specified version
auto_detect_solc = false


# Optimization settings
optimizer = true
optimizer_runs = 200


# Set the EVM version
evm_version = "prague"


